# Generated by Django 5.2 on 2025-05-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='weather_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
